name: 'Get Affected Crates'
description: 'Creates a matrix of all crates affected by the event'
inputs:
  added:
    description: "files modified or added by event"
    required: false
  deleted:
    description: "files deleted by change"
    required: false
  renamed:
    description: "files rename by change"
    required: false
  modified: 
    description: "files modified by change"
    required: false

outputs:
  matrix:
    description: "Matrix of Affected Crates"
    value: ${{ steps.gen-matrix.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: "setup node"
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install find-up@v5.0.0
      shell: bash
    - name: Generate Testing Matrix
      uses: actions/github-script@v4.1
      id: gen-matrix
      with:
        script: |
          const {generateBuildMatrix} = require('${{ github.action_path}}/gen-matrix')
          const files = [${{inputs.added}}, ${{inputs.deleted}}, $${{inputs.renamed}}, {{inputs.modified}}].flat()
          let matrix = await generateBuildMatrix(files)
          console.log('matrix:', matrix)
          return matrix
